/**
 * Helpers for responsive images served from the variant ladders exposed by the
 * API (thumb/small/medium/large/original). Variant widths differ between post
 * featured images and product DAM images, so each caller picks a ladder.
 */

export type ImageVariantKey = 'thumb' | 'small' | 'medium' | 'large' | 'original'

export type ImageUrls = Partial<Record<ImageVariantKey, string | null>>

export interface ImageLadderEntry {
  key: ImageVariantKey
  width: number
}

/** Post featured images (generated by the admin uploader). */
export const POST_IMAGE_LADDER: ImageLadderEntry[] = [
  { key: 'small', width: 640 },
  { key: 'medium', width: 1024 },
  { key: 'large', width: 1500 },
]

/** Product DAM images (original/large 1500 / medium 800 / small 300 / thumb 100). */
export const PRODUCT_IMAGE_LADDER: ImageLadderEntry[] = [
  { key: 'small', width: 300 },
  { key: 'medium', width: 800 },
  { key: 'large', width: 1500 },
]

/**
 * Build a `srcset` value from the available variant URLs, in the order of the
 * given ladder. Null/missing variants are skipped; returns undefined when no
 * candidate exists.
 */
export function buildSrcset(
  urls: ImageUrls | null | undefined,
  ladder: ImageLadderEntry[]
): string | undefined {
  if (!urls) return undefined

  const candidates = ladder
    .map(({ key, width }) => {
      const url = urls[key]
      return url ? `${url} ${width}w` : null
    })
    .filter((candidate): candidate is string => candidate !== null)

  return candidates.length > 0 ? candidates.join(', ') : undefined
}

/**
 * Return the first available URL by preference order (used for the `src`
 * fallback that renders when srcset is unsupported).
 */
export function preferUrl(
  urls: ImageUrls | null | undefined,
  preference: ImageVariantKey[]
): string | undefined {
  if (!urls) return undefined
  for (const key of preference) {
    const url = urls[key]
    if (url) return url
  }
  return undefined
}
